const jobMockData = [
  {
    id: 1,
    title: "Software Engineer",
    position: "Software Engineer",
    company: "Google",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    location: "Hanoi, Vietnam",
    createdAt: "30/09/2023",
    closedDate: "01 / 01 / 2024",
    applicants: "200",
    field: "Engineering",
    salary: "$100K - $120K",
    logo: "https://i.pravatar.cc/256",
  },
  {
    title: "Software Engineer",
    company: "Tech Solutions Inc.",
    logo: "https://i.pravatar.cc/256",
    createdAt: "2023-10-01",
    closedDate: "2023-11-15",
    salary: "$80,000 - $100,000",
    location: "San Francisco, USA",
    field: "Information Technology",
    position: "Full-stack Developer",
    status: "active",
    maxApplicants: 50,
    description:
      "We are seeking a talented Software Engineer to join our dynamic team. The ideal candidate has experience in full-stack development, a passion for problem-solving, and a strong desire to innovate.",
    applicants: [],
  },
  {
    title: "Marketing Manager",
    company: "Global Marketing Agency",
    logo: "https://i.pravatar.cc/256",
    createdAt: "2023-09-15",
    closedDate: "2023-11-10",
    salary: "$70,000 - $90,000",
    location: "New York City, USA",
    field: "Marketing",
    position: "Marketing Manager",
    status: "active",
    maxApplicants: 30,
    description:
      "Join our marketing team and drive our global marketing efforts to new heights. We're looking for a creative and strategic Marketing Manager to lead campaigns, analyze data, and optimize results.",
    applicants: [],
  },
  {
    title: "Data Analyst",
    company: "Data Insights Ltd.",
    logo: "https://i.pravatar.cc/256",
    createdAt: "2023-09-20",
    closedDate: "2023-10-05",
    salary: "$60,000 - $75,000",
    location: "London, UK",
    field: "Data Science",
    position: "Data Analyst",
    status: "active",
    maxApplicants: 40,
    description:
      "Are you passionate about data analysis and insights? Join our team and work with large datasets to uncover valuable information. We're looking for a skilled Data Analyst to join us.",
    applicants: [],
  },
  {
    title: "Graphic Designer",
    company: "Creative Designs Co.",
    logo: "https://i.pravatar.cc/256",
    createdAt: "2023-09-25",
    closedDate: "2024-01-20",
    salary: "$45,000 - $60,000",
    location: "Los Angeles, USA",
    field: "Design",
    position: "Graphic Designer",
    status: "active",
    maxApplicants: 20,
    description:
      "We're seeking a creative Graphic Designer to bring visual concepts to life. If you have a strong portfolio, an eye for detail, and a passion for design, we'd love to hear from you.",
    applicants: [],
  },
  {
    title: "Sales Representative",
    company: "SalesPro Inc.",
    logo: "https://i.pravatar.cc/256",
    createdAt: "2023-08-30",
    closedDate: "2023-10-05",
    salary: "$50,000 - $70,000",
    location: "Chicago, USA",
    field: "Sales",
    position: "Sales Representative",
    status: "active",
    maxApplicants: 25,
    description:
      "Join our sales team and help us drive revenue growth. We're looking for motivated Sales Representatives who can build and maintain relationships with clients and achieve sales targets.",
    applicants: [],
  },
];

export default jobMockData;
